### ISSUE TITLE
Mlang filter not workin on frontpage

### ISSUE THREAD

**Issue by deivishome** [iarenaza/moodle-atto_multilang2#1]
I use this plugin in ATTO editor with the following code to set Summary of Site information. This is the example code that ATTO shows:
 {mlang es} HOLA{mlang} 
 {mlang en}HELLO{mlang} 

Then I save the changes and in front page shows the same code as above instead only the language that Moodle is using or the browser is using.

Am I doing something wrong?

Thank you very much.

Regards

**Comment by iarenaza** [comment]
A couple of questions, so I can diagnose the problem:
- Have you installed and enabled the multilang2 filter plugin (https://github.com/iarenaza/moodle-filter_multilang2). The Atto plugin only helps create the syntax needed by the filter plugin, but the real work (selecting which string to show based on the browsing language) is done by the filter plugin.
- Are you using a non-standard theme? Some non-standard themes don't use format_string() or format_text() to display the texts, so they don't get processed by the filters (including the multilang filter).

Saludos.
Iñaki.

**Comment by deivishome** [comment]
Hola Iñaki,

Ya vi donde tenia el problema, tenia instalado el plugin multilang 1 y el multilang2.  Despues de desinstalar todo y volver a instalar multilang2 y el atto_multilang2 y reactivar el filtro ahora funciona correctamente.

Uso moodle 3.4 y el template Eguru.

Muchas gracias por tu rapida respuesta.
